### ISSUE TITLE
UserRepository wp_capabilities assumes default wp_ table prefix

### ISSUE THREAD

**Issue by rpkamp** [williarin/wordpress-interop#51]
In the [UserRepository mapping](https://github.com/williarin/wordpress-interop/blob/master/src/Bridge/Repository/UserRepository.php#L48) there is a mapping from `wp_capabilities` to `capabilities`. However, the `wp_` in `wp_capabilities` is the database prefix used for tables. 

So somehow `$this->entityManager->getTablesPrefix()` should be used there, but that's not possible since it's a constant and we can't call class methods in constant creation. 

I can think of two alternatives:

1) Change the `MAPPED_FIELDS` constant to a method `getMappedFields()` that returns the mapping. `$this->entityManager->getTablesPrefix()` can be called from that method (as long as the method isn't static). For BC the method could be optional (i.e. defined on the abstract class via `@method`), if it's missing there is a fallback to `MAPPED_FIELDS` (which is annotated `@deprecated`) until the next major release of this package where `getMappedFields` becomes required and `MAPPED_FIELDS` is gone.

2) Change the key to something like `{{wp_prefix}}capabilities`, and then whenever `MAPPED_FIELDS` is accessed, replace `{{wp_prefix}}` with the value from `$this->entityManager->getTablesPrefix()`. This is a BC break, since the constant is protected and downstream code may depend on its value.

Option 1 seems a little bit nicer, mostly because it offers a clear BC path, but I don't have a clear preference for either.

I wouldn't mind opening a PR for this if you know which direction you'd like to take this.

**Comment by williarin** [comment]
I had no idea this prefix was also dynamic, thanks for the detailed problem and solutions. I think option 1 is nicer too, I don't know why I used a constant in the first place. You're welcome to open a PR for this fix!

**Comment by rpkamp** [comment]
Done :slightly_smiling_face: 

https://github.com/williarin/wordpress-interop/pull/52

**Comment by williarin** [comment]
Thank you!
